import fs from 'fs';
import path from 'path';
import readline from 'readline';
import chalk from 'chalk';

interface InitCommandOptions {
  output?: string;
}

function createReadlineInterface(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl: readline.Interface, question: string, defaultValue?: string): Promise<string> {
  const prompt = defaultValue ? `${question} (${defaultValue}): ` : `${question}: `;
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer.trim() || defaultValue || '');
    });
  });
}

function generateResumeYaml(name: string, email: string, label: string): string {
  return `# =============================================================================
# Resume - Generated by resuml
# Documentation: https://github.com/phoinixi/resuml
# Schema: https://jsonresume.org/schema/
# =============================================================================

# --- Basic Information ---
basics:
  name: '${name}'
  label: '${label}'
  # image: 'https://example.com/photo.jpg'
  email: '${email}'
  # phone: '+1-555-123-4567'
  # url: 'https://yourwebsite.com'
  summary: >-
    Write a short professional summary here.
    This supports multi-line strings in YAML.
  location:
    # address: '123 Main Street'
    # postalCode: '12345'
    city: 'Your City'
    countryCode: 'US'
    # region: 'Your State'
  profiles:
    - network: 'LinkedIn'
      username: 'your-username'
      url: 'https://linkedin.com/in/your-username'
    - network: 'GitHub'
      username: 'your-username'
      url: 'https://github.com/your-username'

# --- Work Experience ---
work:
  - name: 'Company Name'
    position: 'Job Title'
    url: 'https://company.com'
    startDate: '2020-01-01'
    # endDate: '2023-12-31'  # Omit for current position
    summary: 'Brief description of your role and responsibilities.'
    highlights:
      - 'Key achievement or responsibility'
      - 'Another notable accomplishment'

# --- Education ---
education:
  - institution: 'University Name'
    url: 'https://university.edu'
    area: 'Field of Study'
    studyType: 'Bachelor of Science'
    startDate: '2014-09-01'
    endDate: '2018-06-01'
    # score: '3.8'
    courses:
      - 'Relevant Course 1'
      - 'Relevant Course 2'

# --- Skills ---
skills:
  - name: 'Programming Languages'
    level: 'Expert'
    keywords:
      - 'JavaScript'
      - 'TypeScript'
      - 'Python'
  - name: 'Frameworks'
    level: 'Advanced'
    keywords:
      - 'React'
      - 'Node.js'

# --- Projects ---
# projects:
#   - name: 'Project Name'
#     description: 'Brief project description'
#     highlights:
#       - 'Key feature or result'
#     keywords:
#       - 'Technology Used'
#     startDate: '2023-01-01'
#     endDate: '2023-06-30'
#     url: 'https://github.com/you/project'
#     roles:
#       - 'Developer'
#     type: 'application'

# --- Languages ---
# languages:
#   - language: 'English'
#     fluency: 'Native speaker'
#   - language: 'Spanish'
#     fluency: 'Professional working proficiency'

# --- Interests ---
# interests:
#   - name: 'Open Source'
#     keywords:
#       - 'Contributing'
#       - 'Community'

# --- References ---
# references:
#   - name: 'Jane Smith'
#     reference: 'It was a pleasure working with...'

# --- Awards ---
# awards:
#   - title: 'Award Name'
#     date: '2023-01-01'
#     awarder: 'Organization'
#     summary: 'Description of the award'

# --- Certificates ---
# certificates:
#   - name: 'Certificate Name'
#     date: '2023-01-01'
#     issuer: 'Issuing Organization'
#     url: 'https://example.com/cert'

# --- Publications ---
# publications:
#   - name: 'Publication Title'
#     publisher: 'Publisher'
#     releaseDate: '2023-01-01'
#     url: 'https://example.com/publication'
#     summary: 'Brief description'

# --- Volunteer ---
# volunteers:
#   - organization: 'Organization Name'
#     position: 'Volunteer Role'
#     url: 'https://organization.com'
#     startDate: '2022-01-01'
#     summary: 'Description of volunteer work'
#     highlights:
#       - 'Notable contribution'
`;
}

export async function initAction(options: InitCommandOptions): Promise<void> {
  const outputPath = options.output || 'resume.yaml';
  const fullPath = path.resolve(outputPath);

  const rl = createReadlineInterface();

  try {
    // Check if file already exists
    if (fs.existsSync(fullPath)) {
      const overwrite = await ask(
        rl,
        `${chalk.yellow('⚠')}  ${outputPath} already exists. Overwrite? (y/N)`,
        'N'
      );
      if (overwrite.toLowerCase() !== 'y') {
        console.log(chalk.blue('Aborted. No files were changed.'));
        return;
      }
    }

    console.log(chalk.blue('\n📝 Let\'s set up your resume!\n'));

    const name = await ask(rl, 'Your full name', 'John Doe');
    const email = await ask(rl, 'Email address', 'john@example.com');
    const label = await ask(rl, 'Professional title/label', 'Software Engineer');

    const yaml = generateResumeYaml(name, email, label);

    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, yaml, 'utf8');

    console.log(chalk.green(`\n✅ Created ${outputPath}`));
    console.log(chalk.blue('\nNext steps:'));
    console.log(`  1. Edit ${outputPath} to fill in your details`);
    console.log('  2. Run ' + chalk.cyan('resuml validate --resume ' + outputPath));
    console.log('  3. Run ' + chalk.cyan('resuml render --resume ' + outputPath + ' --theme stackoverflow'));
  } finally {
    rl.close();
  }
}
